### ISSUE TITLE
Not an issue: What is the difference with CodevTT plugin ?

### ISSUE THREAD

**Issue by lbayle** [mantisbt-plugins/timetracking#29] opened 2017-05-22 11:47 UTC
Hi,
The CodevTT plugin aims to do some advanced timetracking on Mantis.
I'd be interested in knowing the goal of this new timetracking plugin. Maybe we could join our efforts ?

https://github.com/mantisbt-plugins/codev

Best regards

**Comment by atrol** [comment] 2017-05-22 15:05
> goal of this new timetracking plugin

New? It's there since [2011](https://github.com/mantisbt-plugins/timetracking/graphs/contributors).

**Comment by lbayle** [comment] 2017-05-22 15:12
Oh right, the one from Vincent Sels ! 
my bad, it's not new...

**Comment by atrol** [comment] 2017-05-22 15:29
> Oh right, the one from Vincent Sels !

I don't think so, I assume you mean [this one](https://github.com/vincentsels/ProjectManagement).

There are obviously too many plugins dealing with time tracking and project management ;-)

**Comment by epenet** [comment] 2017-05-22 15:37
And project management adds a lot of overhead when all you want is time tracking.

**Comment by cproensa** [comment] 2017-05-22 15:42
> hope we'll be able to join our efforts some day

In what way could be that done?
This plugin started as a nearly duplicate of mantis native timetracking functionality, with very small variations. In the future we may use this plugin to implement all native functionality to clean up old timetracking code from core.
Anyway, the features are small and very simple
- users can enter one or several "time spent" annotations for each issue. The annotations can be linked with a particular bugnote.
- There are some basic reporting to show time spent per user, between dates, etc.
- a stopwatch widget that allows count time with a clock, with start and stop controls (in mantis native timetracking)
- very simple billing functionality, where you set the pricing per hour, and show the totals over previous reports (in mantis native timetracking)

Note that the time registered by this plugin, is not time elapsed between states, or activities, only the one registered manually by the suer. There are not any automatic time entering.

CodevTT is a more complete solution. Also, IIRC, it doesn't work within the mantis plugin framework, as it is a standalone app, that shares data through direct access to mantis database.

The only way that this could be connected, i think, is that codevTT use the data stored by the timetracking plugin, or that it uses this plugin as the backend for time measures storage/manage

**Closed** 2017-09-18 07:47 UTC
