### ISSUE TITLE
'user' and 'timestamp' are reserved words in postrges

### ISSUE THREAD

**Issue by angmac** [mantisbt-plugins/timetracking#14] opened 2014-04-09 17:39 UTC
Mantis translate the schema definition to the following:
CREATE TABLE mantis_plugin_TimeTracking_data_table (
        id                       SERIAL,
        bug_id                   INTEGER DEFAULT NULL,
        user                     INTEGER DEFAULT NULL,
        expenditure_date         TIMESTAMP DEFAULT NULL,
        hours                    FLOAT8 DEFAULT NULL,
        timestamp                TIMESTAMP DEFAULT NULL,
        info                     VARCHAR(255) DEFAULT NULL,
                         PRIMARY KEY (id)
        )
and because user and timestamp are reserved words in postgres it throws error.

**Comment by dregad** [comment] 2018-04-12 07:59
Closing as duplicate of #36

**Closed by dregad** 2018-04-12 07:59 UTC
